spring:
  datasource:
    username: root
    password: Sandeep11
    url: jdbc:mysql://localhost:3306/jrtp
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true